### ISSUE TITLE
CS security group specification doesn't work

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#356]
In cloud_resources.conf we have 
security_group:    HTCondorWorker

specified for two clouds. I have created the "HTCondorWorker" security group in the dashboard in the appropriate tenant on those clouds.

However, VMs booted by CS on those clouds use the "default" security group.

The logs also show:
2015-01-28 02:52:08,606 - DEBUG - Scheduler - No matching security groups - trying default config

**Comment by berghaus** [comment]
Yes, I remember doing that - I thought it was better to create a new group then just editing the default. There was some issue that cloud scheduler did not pick up the new security group and ended up using the default one, but I don’t recall what that issue was. Mike do you recall?

Cheers,
-Frank



On 28 Jan 2015, at 23:31, rptaylor <notifications@github.com<mailto:notifications@github.com>> wrote:


In cloud_resources.conf we have
security_group: HTCondorWorker

specified for two clouds. I have created the "HTCondorWorker" security group in the dashboard in the appropriate tenant on those clouds.

However, VMs booted by CS on those clouds use the "default" security group.

The logs also show:
2015-01-28 02:52:08,606 - DEBUG - Scheduler - No matching security groups - trying default config

**Comment by mhpx** [comment]
The issue is most of the CS machines had not been updated to include this feature.
